/* Aniket Nutrition v3 — local-first nutrition engine
   RULES:
   • Database values are used only for foods present in the local database.
   • User-entered custom-food values are kept separate and labelled as user-entered.
   • Unknown foods never receive invented nutrition values.
   • The interpreter may parse natural language, but calculations are performed here.
*/
const KEY='aniketNutritionV3';
const IFCT_CACHE_KEY='aniketNutritionIFCT2017';
const IFCT_MANIFEST_KEY='aniketNutritionIFCTManifest';
const PROFILE={age:24,sex:'male',weight:63,heightIn:69,targetWeightMin:68,targetWeightMax:69,bodyFatMax:18};
const TARGET={kcal:2450,protein:130,carbs:315,fat:75,fiber:35};
const MICRO={
 calcium:{name:'Calcium',unit:'mg',target:1000},iron:{name:'Iron',unit:'mg',target:8},magnesium:{name:'Magnesium',unit:'mg',target:400},
 vitaminC:{name:'Vitamin C',unit:'mg',target:90},zinc:{name:'Zinc',unit:'mg',target:11},folate:{name:'Folate',unit:'µg',target:400},
 vitaminD:{name:'Vitamin D',unit:'µg',target:15},vitaminB12:{name:'Vitamin B12',unit:'µg',target:2.4},vitaminA:{name:'Vitamin A',unit:'µg RAE',target:900},potassium:{name:'Potassium',unit:'mg',target:3400},
 omega3:{name:'Omega-3 (ALA+EPA+DHA)',unit:'g',target:1.6}
};
const FOOD_NUTRIENTS=['kcal','protein','carbs','fat','fiber',...Object.keys(MICRO)];
// Local food records. Values are per stated serving/base; they are not generated by AI.
// Provenance schema mirrors traceable food-composition records: source, sourceId, foodState, basis, ediblePortionPct, servingGrams.
const DATA_SOURCES={ifct2017:{name:'ICMR-NIN IFCT 2017',url:'https://www.nin.res.in/ebooks/IFCT2017_16122024.pdf'},usda_fdc:{name:'USDA FoodData Central',url:'https://fdc.nal.usda.gov/'} };
const DEFAULT_RECORD_META={sourceType:'reference_estimate',sourceId:null,foodState:'unspecified',basis:'per 100 g edible portion',ediblePortionPct:null,servingGrams:null};
const VERIFIED_IFCT = [
  {id:'ifct_M001',name:'Egg, poultry, whole, raw',serving:'1 egg (50 g)',base:100,nutrients:{kcal:564/4.18,protein:13.28,carbs:null,fat:9.15,fiber:null,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'M001',foodState:'raw',basis:'per 100 g edible portion',servingGrams:50},
  {id:'ifct_M004',name:'Egg, poultry, whole, boiled',serving:'1 egg (50 g)',base:100,nutrients:{kcal:618/4.18,protein:13.43,carbs:null,fat:10.54,fiber:null,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'M004',foodState:'boiled',basis:'per 100 g edible portion',servingGrams:50},
  {id:'ifct_N003',name:'Chicken, poultry, breast, skinless',serving:'100 g',base:100,nutrients:{kcal:704/4.18,protein:21.81,carbs:null,fat:9.00,fiber:null,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'N003',foodState:'raw',basis:'per 100 g edible portion',servingGrams:100},
  {id:'ifct_A019',name:'Wheat flour, atta',serving:'100 g',base:100,nutrients:{kcal:1340/4.18,protein:10.57,carbs:64.17,fat:1.53,fiber:11.36,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'A019',foodState:'raw',basis:'per 100 g edible portion',servingGrams:100},
  {id:'ifct_B013',name:'Lentil dal',serving:'100 g',base:100,nutrients:{kcal:1349/4.18,protein:24.35,carbs:52.53,fat:.75,fiber:10.43,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'B013',foodState:'raw',basis:'per 100 g edible portion',servingGrams:100},
  {id:'ifct_B001',name:'Bengal gram, dal',serving:'100 g',base:100,nutrients:{kcal:1377/4.18,protein:21.55,carbs:46.72,fat:5.31,fiber:12.67,calcium:null,iron:null,magnesium:null,vitaminC:null,zinc:null,folate:null,vitaminD:null,vitaminB12:null,vitaminA:null,potassium:null,omega3:null},source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:'B001',foodState:'raw',basis:'per 100 g edible portion',servingGrams:100}
];
const FOODS=[
 ['rice_cooked','Cooked white rice','100 g',100,{kcal:130,protein:2.7,carbs:28.2,fat:.3,fiber:.4,calcium:10,iron:.2,magnesium:12,vitaminC:0,zinc:.5,folate:58,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:35,omega3:.01},'Reference estimate — source record not yet verified'],
 ['roti','Roti / chapati','1 piece (40 g)',40,{kcal:120,protein:3.5,carbs:24,fat:1.5,fiber:3,calcium:14,iron:1.2,magnesium:25,vitaminC:0,zinc:.7,folate:20,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:95,omega3:.02},'Reference estimate — source record not yet verified'],
 ['egg','Whole egg','1 large (50 g)',50,{kcal:72,protein:6.3,carbs:.4,fat:4.8,fiber:0,calcium:28,iron:.9,magnesium:6,vitaminC:0,zinc:.6,folate:24,vitaminD:1.1,vitaminB12:.5,vitaminA:80,potassium:69,omega3:.04},'Reference estimate — source record not yet verified'],
 ['chicken','Chicken breast, cooked','100 g',100,{kcal:165,protein:31,carbs:0,fat:3.6,fiber:0,calcium:15,iron:1,magnesium:29,vitaminC:0,zinc:1,folate:4,vitaminD:.1,vitaminB12:.3,vitaminA:6,potassium:256,omega3:.03},'Reference estimate — source record not yet verified'],
 ['paneer','Paneer','100 g',100,{kcal:265,protein:18.3,carbs:6.1,fat:20.8,fiber:0,calcium:208,iron:2.2,magnesium:8,vitaminC:0,zinc:2.3,folate:20,vitaminD:.1,vitaminB12:1.2,vitaminA:210,potassium:104,omega3:.1},'Reference estimate — source record not yet verified'],
 ['tofu','Firm tofu','100 g',100,{kcal:144,protein:17.3,carbs:2.8,fat:8.7,fiber:2.3,calcium:350,iron:5.4,magnesium:60,vitaminC:0,zinc:1.5,folate:29,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:237,omega3:.4},'Reference estimate — source record not yet verified'],
 ['dal_toor','Cooked toor dal','100 g',100,{kcal:137,protein:9,carbs:23,fat:1.2,fiber:7.7,calcium:43,iron:2.2,magnesium:36,vitaminC:1.8,zinc:1.1,folate:66,vitaminD:0,vitaminB12:0,vitaminA:1,potassium:266,omega3:.04},'Reference estimate — source record not yet verified'],
 ['dal_masoor','Cooked masoor dal','100 g',100,{kcal:116,protein:9,carbs:20,fat:.4,fiber:7.9,calcium:19,iron:3.3,magnesium:36,vitaminC:1.5,zinc:1.3,folate:181,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:369,omega3:.04},'Reference estimate — source record not yet verified'],
 ['chana','Cooked chickpeas','100 g',100,{kcal:164,protein:8.9,carbs:27.4,fat:2.6,fiber:7.6,calcium:49,iron:2.9,magnesium:48,vitaminC:1.3,zinc:1.5,folate:172,vitaminD:0,vitaminB12:0,vitaminA:1,potassium:291,omega3:.05},'Reference estimate — source record not yet verified'],
 ['milk','Cow milk, whole','100 ml',100,{kcal:61,protein:3.2,carbs:4.8,fat:3.3,fiber:0,calcium:113,iron:0,magnesium:10,vitaminC:0,zinc:.4,folate:5,vitaminD:1,vitaminB12:.4,vitaminA:46,potassium:132,omega3:.04},'Reference estimate — source record not yet verified'],
 ['curd','Plain curd / yogurt','100 g',100,{kcal:61,protein:3.5,carbs:4.7,fat:3.3,fiber:0,calcium:121,iron:0,magnesium:12,vitaminC:.5,zinc:.5,folate:7,vitaminD:.1,vitaminB12:.4,vitaminA:27,potassium:155,omega3:.04},'Reference estimate — source record not yet verified'],
 ['banana','Banana','1 medium (118 g)',118,{kcal:105,protein:1.3,carbs:27,fat:.4,fiber:3.1,calcium:6,iron:.3,magnesium:32,vitaminC:10.3,zinc:.2,folate:24,vitaminD:0,vitaminB12:0,vitaminA:3,potassium:422,omega3:.03},'Reference estimate — source record not yet verified'],
 ['oats','Rolled oats, dry','100 g',100,{kcal:389,protein:16.9,carbs:66.3,fat:6.9,fiber:10.6,calcium:54,iron:4.7,magnesium:177,vitaminC:0,zinc:4,folate:56,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:429,omega3:.11},'Reference estimate — source record not yet verified'],
 ['peanut','Peanuts, roasted','100 g',100,{kcal:567,protein:25.8,carbs:16.1,fat:49.2,fiber:8.5,calcium:92,iron:4.6,magnesium:168,vitaminC:0,zinc:3.3,folate:240,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:705,omega3:.03},'Reference estimate — source record not yet verified'],
 ['pumpkin_seed','Pumpkin seeds','100 g',100,{kcal:559,protein:30.2,carbs:10.7,fat:49.1,fiber:6,calcium:46,iron:8.8,magnesium:592,vitaminC:1.9,zinc:7.6,folate:58,vitaminD:0,vitaminB12:0,vitaminA:16,potassium:919,omega3:.12},'Reference estimate — source record not yet verified'],
 ['poha','Poha / flattened rice, cooked','100 g',100,{kcal:130,protein:2.4,carbs:27,fat:1.2,fiber:1.5,calcium:10,iron:1.1,magnesium:15,vitaminC:0,zinc:.5,folate:10,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:30,omega3:.02},'Reference estimate — source record not yet verified'],
 ['sattu','Sattu / roasted gram flour','100 g',100,{kcal:400,protein:20,carbs:58,fat:7,fiber:12,calcium:100,iron:4.5,magnesium:160,vitaminC:0,zinc:3,folate:180,vitaminD:0,vitaminB12:0,vitaminA:0,potassium:700,omega3:.05},'Reference estimate — source record not yet verified']
].map(([id,name,serving,base,nutrients,source])=>({id,name,serving,base,nutrients,source,...DEFAULT_RECORD_META,sourceType:'reference_estimate',sourceId:null,foodState:/cooked/i.test(name)?'cooked':'unspecified',basis:'reference estimate per 100 g or stated serving',servingGrams:base}));
const foodMap=Object.fromEntries(FOODS.map(f=>[f.id,f]));
const FOOD_ALIASES={ifct_A019:['atta','wheat flour','gehun atta'],ifct_B013:['lentil dal','masoor dal','masur dal'],ifct_B001:['bengal gram dal','chana dal'],ifct_M001:['ifct egg','egg poultry whole raw'],ifct_M004:['boiled egg','egg boiled'],ifct_N003:['chicken breast','chicken poultry breast']};
const FOOD_ALIASES_OLD={rice_cooked:['rice','cooked rice','chawal','bhaat'],roti:['chapati','roti','phulka','fulka'],egg:['egg','eggs','anda','ande'],chicken:['chicken','chicken breast','murgi'],paneer:['paneer','cottage cheese'],tofu:['tofu','soy tofu'],dal_toor:['toor dal','arhar dal','tuvar dal','pigeon pea dal','dal'],dal_masoor:['masoor dal','red lentil dal'],chana:['chana','chickpeas','kabuli chana','chole'],milk:['milk','doodh','cow milk'],curd:['curd','dahi','yogurt','yoghurt'],banana:['banana','kela'],oats:['oats','rolled oats'],peanut:['peanut','peanuts','groundnut','moongfali'],pumpkin_seed:['pumpkin seed','pumpkin seeds','kaddu seed'],poha:['poha','flattened rice','chiwda','chivda'],sattu:['sattu','roasted gram flour']};
for(const [id,aliasesList] of Object.entries(FOOD_ALIASES)){if(foodMap[id])foodMap[id].aliases=aliasesList;}
const aliases={rice:'rice_cooked','cooked rice':'rice_cooked','white rice':'rice_cooked','chapati':'roti','roti':'roti','egg':'egg','eggs':'egg','chicken':'chicken','chicken breast':'chicken','paneer':'paneer','tofu':'tofu','toor dal':'dal_toor','arhar dal':'dal_toor','masoor dal':'dal_masoor','dal':'dal_toor','chickpeas':'chana','chana':'chana','milk':'milk','curd':'curd','yogurt':'curd','banana':'banana','oats':'oats','peanuts':'peanut','peanut':'peanut','pumpkin seeds':'pumpkin_seed','poha':'poha','sattu':'sattu'};
const DEFAULT={profile:PROFILE,days:{},customFoods:[],recipes:[],reminders:{omega3:false,d3:false,b12:false},lastGapScan:null};
let state=load(); const today=localDate(); ensureDay(today); migrate(); save();
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('aniketNutritionV2')||'{}';const x=JSON.parse(raw);return {...structuredClone(DEFAULT),...x,profile:{...PROFILE,...(x.profile||{})},reminders:{...DEFAULT.reminders,...(x.reminders||{})}}}catch{return structuredClone(DEFAULT)}}
function migrate(){for(const d of Object.values(state.days||{})){for(const x of d.items||[]){if(x.source==='Reference estimate — source record not yet verified')x.dataType='estimate';if(!x.id)x.id=crypto.randomUUID()}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function localDate(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function ensureDay(date){if(!state.days[date])state.days[date]={items:[]}}
function dayItems(date=today){ensureDay(date);return state.days[date].items}
function sum(items=dayItems()){return FOOD_NUTRIENTS.reduce((a,k)=>(a[k]=(items||[]).reduce((s,x)=>s+(Number(x.nutrients?.[k])||0),0),a),{})}
function scale(n,amount,base=100){const r={};for(const k of Object.keys(n))r[k]=n[k]==null?null:Number(n[k])*amount/base;return r}

/* IFCT 2017 local sync layer.
   Source package: @ifct2017/compositions 2.0.9, derived from ICMR-NIN IFCT 2017.
   The app stores the downloaded records locally; it never guesses missing nutrients. */
const IFCT_URLS=[
  'https://unpkg.com/@ifct2017/compositions@2.0.9/assets/01.csv',
  'https://unpkg.com/@ifct2017/compositions@2.0.9/files/index.csv'
];
function csvRows(text){
  const rows=[]; let row=[], cell='', quoted=false;
  for(let i=0;i<text.length;i++){
    const c=text[i], n=text[i+1];
    if(quoted){ if(c==='"'&&n==='"'){cell+='"';i++;} else if(c==='"') quoted=false; else cell+=c; }
    else if(c==='"') quoted=true;
    else if(c===','){row.push(cell);cell='';}
    else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell='';}
    else if(c!=='\r') cell+=c;
  }
  if(cell.length||row.length){row.push(cell);rows.push(row)}
  return rows;
}
function numOrNull(v){if(v==null||String(v).trim()===''||String(v).trim().toUpperCase()==='NA')return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null}
function findCol(headers,code){const i=headers.findIndex(h=>String(h).split(';')[1]?.trim()===code);return i>=0?i:headers.findIndex(h=>String(h).trim()===code)}
function makeIfctFood(headers,row){
  const get=c=>numOrNull(row[findCol(headers,c)]);
  const code=row[0], name=row[1];
  if(!code||!name)return null;
  const kcal=get('enerc'), protein=get('protcnt'), fat=get('fatce'), fiber=get('fibtg'), carbs=get('choavldf');
  const nutrients={kcal,protein,carbs,fat,fiber,calcium:get('ca'),iron:get('fe'),magnesium:get('mg'),vitaminC:get('vitc'),zinc:get('zn'),folate:get('folsum'),vitaminD:get('vitd'),vitaminB12:null,vitaminA:get('vita'),potassium:get('k'),omega3:(get('f18d3n3')!=null||get('f20d5n3')!=null||get('f22d6n3')!=null)?((get('f18d3n3')||0)+(get('f20d5n3')||0)+(get('f22d6n3')||0))/1000:null};
  const hasCore=[kcal,protein,carbs,fat].some(v=>v!=null);
  if(!hasCore)return null;
  return {id:'ifct2017_'+code,name,serving:'100 g',base:100,nutrients,source:'ICMR-NIN IFCT 2017',sourceType:'database',sourceId:code,foodState:'raw/as-listed',basis:'per 100 g edible portion',ediblePortionPct:100,servingGrams:100,aliases:[]};
}
async function syncIFCT(){
  const st=document.getElementById('syncStatus');
  if(st)st.textContent='Downloading IFCT 2017…';
  try{
    let text=null,lastErr=null;
    for(const url of IFCT_URLS){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){text=await r.text();break}lastErr=new Error('HTTP '+r.status)}catch(e){lastErr=e}}
    if(!text)throw lastErr||new Error('Download failed');
    const rows=csvRows(text); const headers=rows.shift()||[];
    const foods=rows.map(r=>makeIfctFood(headers,r)).filter(Boolean);
    if(foods.length<50)throw new Error('Downloaded file did not contain enough food records');
    localStorage.setItem(IFCT_CACHE_KEY,JSON.stringify(foods));
    localStorage.setItem(IFCT_MANIFEST_KEY,JSON.stringify({count:foods.length,updatedAt:new Date().toISOString(),source:'@ifct2017/compositions 2.0.9 / ICMR-NIN IFCT 2017'}));
    if(st)st.textContent=`✓ Synced ${foods.length} IFCT records. Stored locally for offline use.`;
    render();
  }catch(e){if(st)st.textContent=`⚠️ IFCT sync failed: ${e.message}. Existing database unchanged.`}
}
function getSyncedIfct(){try{const x=JSON.parse(localStorage.getItem(IFCT_CACHE_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function allFoods(){return [...VERIFIED_IFCT,...getSyncedIfct(),...FOODS,...state.customFoods.map(f=>({...f,base:100,serving:'100 g',source:f.source||'User-entered verified label/value',sourceType:'user_entered',foodState:f.foodState||'as-labelled',basis:f.basis||'per 100 g as entered',servingGrams:100}))]}
function resolveFood(name){const q=name.toLowerCase().trim();const foods=allFoods();const exact=foods.find(f=>f.name.toLowerCase()===q);if(exact)return exact;const alias=Object.keys(aliases).find(a=>q===a||q.includes(a));if(alias){const id=aliases[alias];const hit=foods.find(f=>f.id===id);if(hit)return hit;}return foods.find(f=>(f.aliases||[]).some(a=>q===a||q.includes(a)))||null}
function parseQty(q,food){
 const text=String(q||'').toLowerCase().trim();
 const m=text.match(/(\d+(?:\.\d+)?)\s*(kg|g|ml|l|cup|cups|tbsp|tablespoon|tablespoons|tsp|teaspoon|teaspoons|piece|pieces|pcs|egg|eggs|medium|large|small)?/);
 if(!m)return food?.base||100;
 const v=parseFloat(m[1]); const u=m[2]||'';
 const servings=food?.servingGrams||food?.base||100;
 if(u==='kg')return v*1000; if(u==='g')return v; if(u==='l')return v*1000; if(u==='ml')return v;
 if(['cup','cups'].includes(u))return v*(food?.servingConversions?.cup||240);
 if(['tbsp','tablespoon','tablespoons'].includes(u))return v*(food?.servingConversions?.tbsp||15);
 if(['tsp','teaspoon','teaspoons'].includes(u))return v*(food?.servingConversions?.tsp||5);
 if(['piece','pieces','pcs','egg','eggs','medium','large','small'].includes(u))return v*servings;
 return v;
}
function makeItem(food,qty,meal){const amount=parseQty(qty,food);return {id:crypto.randomUUID(),meal,food:food.name,qty:qty||food.serving,foodId:food.id,nutrients:scale(food.nutrients,amount,food.base||100),dataType:food.id.startsWith('custom_')?'user-entered':(food.source?.startsWith('Reference estimate')?'estimate':'database'),source:food.source,sourceType:food.sourceType||'unknown',sourceId:food.sourceId||null,foodState:food.foodState||'unspecified',basis:food.basis||null,ediblePortionPct:food.ediblePortionPct??null,loggedAt:new Date().toISOString()}}
function addFoodByName(name,qty,meal){const food=resolveFood(name);if(!food)return {ok:false,reason:'not_found',name};const item=makeItem(food,qty,meal);dayItems().push(item);return {ok:true,item}}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pct(v,t){return t?Math.min(150,v/t*100):0}
function render(){const t=sum();['kcal','protein','carbs','fat','fiber'].forEach(k=>{const el=document.getElementById(k);if(el)el.textContent=Math.round(t[k]||0)});document.getElementById('calRing').textContent=Math.round((t.kcal||0)/TARGET.kcal*100)+'%';
 const meals=['Breakfast','Afternoon','Dinner','Snacks'];document.getElementById('meals').innerHTML=meals.map(m=>{const a=dayItems().filter(x=>x.meal===m);return `<div class="meal"><strong>${m}</strong>${a.length?a.map(x=>`<div class="food-row"><span>✓ ${esc(x.food)} <small>${esc(x.qty)} · ${x.dataType==='database'?'DB':x.dataType==='estimate'?'Estimate':'Custom'}</small></span><b>${Math.round(x.nutrients.kcal||0)} kcal</b></div>`).join(''):'<span class="muted">Nothing logged</span>'}</div>`}).join('');
 document.getElementById('entries').innerHTML=dayItems().length?dayItems().map((x,i)=>`<div class="food-row entry"><span>${esc(x.meal)} — ${esc(x.food)} · ${esc(x.qty)}<small>${x.dataType==='database'?'Verified database value':x.dataType==='estimate'?'Reference estimate':'User-entered value'} · ${esc(x.source||'')}</small></span><button onclick="removeItem(${i})">×</button></div>`).join(''):'<p class="muted">No entries yet.</p>';
 document.getElementById('micro').innerHTML=Object.entries(MICRO).map(([k,v])=>{const p=pct(t[k]||0,v.target);const c=p>=90?'green':p>=60?'yellow':'red';return `<div class="coverage"><div class="cover-label"><span>${v.name}</span><b>${Math.round(p)}%</b></div><div class="bar"><div class="fill ${c}" style="width:${Math.min(100,p)}%"></div></div><small>${(t[k]||0).toFixed(k==='omega3'||k==='vitaminD'||k==='vitaminB12'?1:0)} / ${v.target} ${v.unit}</small></div>`}).join('');
 document.querySelectorAll('[data-supp]').forEach(x=>x.checked=!!state.reminders[x.dataset.supp]);renderTargets(t);renderWeekly();renderGaps();renderFoodSearch();renderCustomFoods();renderRecipes();renderReminderBanner();
}
function renderTargets(t){const box=document.getElementById('macroTargets');if(!box)return;box.innerHTML=Object.entries({kcal:TARGET.kcal,protein:TARGET.protein,carbs:TARGET.carbs,fat:TARGET.fat,fiber:TARGET.fiber}).map(([k,v])=>`<div><span>${k==='kcal'?'Calories':k[0].toUpperCase()+k.slice(1)}</span><b>${Math.round(t[k]||0)} / ${v}${k==='kcal'?' kcal':'g'}</b></div>`).join('')}
function recipeNutrients(ingredients){const out={};for(const ing of ingredients){const f=resolveFood(ing.name);if(!f)continue;const n=scale(f.nutrients,parseQty(ing.qty,f),f.base||100);Object.entries(n).forEach(([k,v])=>out[k]=(out[k]||0)+v)}return out}
function parseIngredients(raw){return raw.split(',').map(x=>{const m=x.trim().match(/^([\d.]+\s*(?:kg|g|ml|piece|pieces|pcs|egg|eggs|medium|large|small)?)\s+(.+)$/i);return m?{qty:m[1],name:m[2].trim()}:{qty:'100 g',name:x.trim()}})}
function saveRecipe(){const name=document.getElementById('recipeName')?.value.trim(),raw=document.getElementById('recipeIngredients')?.value.trim(),st=document.getElementById('recipeStatus');if(!name||!raw){st.textContent='Enter a recipe name and ingredients.';return}const ingredients=parseIngredients(raw),unknown=ingredients.filter(x=>!resolveFood(x.name));if(unknown.length){st.textContent='⚠️ Unknown ingredient: '+unknown.map(x=>x.name).join(', ')+'. Recipe was not saved.';return}state.recipes.push({id:'recipe_'+crypto.randomUUID(),name,ingredients,nutrients:recipeNutrients(ingredients),source:'Calculated from local database ingredients'});save();st.textContent='✓ Recipe saved.';document.getElementById('recipeName').value='';document.getElementById('recipeIngredients').value='';render()}
function sourceBadge(f){return f.sourceType==='user_entered'||f.id.startsWith('custom_')?'USER':(f.sourceType==='reference_estimate'||f.source?.startsWith('Reference estimate')?'ESTIMATE':(f.sourceType==='ifct2017'||f.sourceType==='usda_fdc'?'DB':'UNVERIFIED'))}
function sourceLabel(f){const b=sourceBadge(f);return b==='USER'?'User-entered':b==='ESTIMATE'?'Reference estimate':b==='DB'?`${DATA_SOURCES[f.sourceType]?.name||'Verified database'}${f.sourceId?' · '+f.sourceId:''}`:'Unverified'}
function provenanceLine(f){return `${sourceLabel(f)} · ${f.foodState||'state unspecified'} · ${f.basis||'basis unspecified'}`}
function renderFoodSearch(){const q=(document.getElementById('foodSearch')?.value||'').toLowerCase();const box=document.getElementById('foodResults');if(!box)return;const a=allFoods().filter(f=>f.name.toLowerCase().includes(q)).slice(0,12);box.innerHTML=a.map(f=>`<button class="food-choice" onclick="selectFood('${f.id}')"><span><b>${esc(f.name)}</b><small>${esc(f.serving)} · ${esc(sourceLabel(f))}</small></span><b>${f.nutrients.kcal} kcal</b></button>`).join('')||'<span class="muted">No database match. Unknown foods are not assigned nutrients.</span>'}
function selectFood(id){const f=allFoods().find(x=>x.id===id);if(!f)return;document.getElementById('food').value=f.name;document.getElementById('qty').value=f.serving;document.getElementById('foodResults').innerHTML=`<div class="selected">✓ Match: ${esc(f.name)} · ${sourceBadge(f)==='USER'?'User-entered':sourceBadge(f)==='ESTIMATE'?'Reference estimate':'Verified database value'}</div>`}
function renderCustomFoods(){const box=document.getElementById('customList');if(!box)return;box.innerHTML=state.customFoods.length?state.customFoods.map(f=>`<div class="saved-row"><span><b>${esc(f.name)}</b><small>${f.nutrients.kcal} kcal · ${f.nutrients.protein||0}g protein / 100g</small></span><button onclick="deleteCustom('${f.id}')">×</button></div>`).join(''):'<span class="muted">No custom foods saved.</span>'}
function renderRecipes(){const box=document.getElementById('recipeList');if(!box)return;box.innerHTML=state.recipes.length?state.recipes.map(r=>`<div class="saved-row"><span><b>${esc(r.name)}</b><small>${r.ingredients.map(i=>esc(i.qty+' '+i.name)).join(', ')}</small></span><button onclick="logRecipe('${r.id}')">Add</button></div>`).join(''):'<span class="muted">No recipes saved.</span>'}
function renderWeekly(){const dates=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);dates.push(localDate(d))}const av={kcal:0,protein:0,carbs:0,fat:0,fiber:0};dates.forEach(d=>{const s=sum(state.days[d]?.items||[]);Object.keys(av).forEach(k=>av[k]+=s[k]||0)});Object.keys(av).forEach(k=>av[k]/=7);const el=document.getElementById('weeklyAverages');if(el)el.innerHTML=Object.entries(av).map(([k,v])=>`<div><span>${k==='kcal'?'Calories':k[0].toUpperCase()+k.slice(1)}</span><b>${Math.round(v)}${k==='kcal'?' kcal':' g'}</b><small>target ${TARGET[k]}${k==='kcal'?' kcal':'g'}</small></div>`).join('');const hist=document.getElementById('weekDays');if(hist)hist.innerHTML=dates.map(d=>{const s=sum(state.days[d]?.items||[]);return `<div class="day-row"><b>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</b><span>${Math.round(s.kcal||0)} kcal</span><span>${Math.round(s.protein||0)}g protein</span><span>${state.days[d]?.items?.length||0} foods</span></div>`}).join('')}
function renderDataNotice(){const el=document.getElementById('dataNotice');if(!el)return;el.innerHTML='<b>Nutrition data status</b><br><b>Database</b> records must carry a source + record ID. <b>Reference estimates</b> remain clearly labelled until verified. <b>User-entered</b> values stay separate. Unknown foods receive no nutrition values.<br><small>IFCT sync can import the locally cached composition catalog. Missing nutrients remain unknown. IFCT 2017: 528 foods, unique food IDs; most values are raw-food analytical data, with egg/poultry exceptions.</small>';}
function renderGaps(){const el=document.getElementById('gaps');if(!el)return;const dates=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);dates.push(localDate(d))}const low=[];for(const [k,v] of Object.entries(MICRO)){const dayVals=dates.map(d=>{const items=state.days[d]?.items||[];const known=items.filter(x=>x.nutrients&&x.nutrients[k]!=null);return known.length?known.reduce((a,x)=>a+(Number(x.nutrients[k])||0),0):null});const knownDays=dayVals.filter(v=>v!=null);if(!knownDays.length)continue;const avg=knownDays.reduce((a,b)=>a+b,0)/knownDays.length;if(avg<v.target*.7)low.push({k,v,avg})}el.innerHTML=low.length?low.map(g=>{const suggestions=allFoods().filter(f=>(f.nutrients[g.k]||0)>0).sort((a,b)=>(b.nutrients[g.k]||0)-(a.nutrients[g.k]||0)).slice(0,3);return `<div class="gap"><b>${g.v.name}</b><span>7-day average: ${g.avg.toFixed(1)} ${g.v.unit} (${Math.round(g.avg/g.v.target*100)}%)</span><small>Food ideas: ${suggestions.map(x=>x.name).join(', ')||'No local food match yet.'}</small></div>`}).join(''):'<div class="good">✓ No persistent micronutrient gaps detected at the current 7-day threshold.</div>'}
function removeItem(i){dayItems().splice(i,1);save();render()}
function deleteCustom(id){state.customFoods=state.customFoods.filter(x=>x.id!==id);save();render()}
function logRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;const meal=document.getElementById('meal').value;dayItems().push({id:crypto.randomUUID(),meal,food:r.name,qty:'1 recipe',foodId:r.id,nutrients:r.nutrients,dataType:'calculated-recipe',source:r.source,sourceType:'calculated_recipe',sourceId:r.id,foodState:'as-prepared',basis:'calculated from saved ingredients',loggedAt:new Date().toISOString()});save();render();document.getElementById('recipeStatus').textContent=`✓ Added ${r.name} to ${meal}.`}
function tokenizeNatural(text){return text.toLowerCase().replace(/\band\b/g,',').split(/[,;]|\s+then\s+/).map(x=>x.trim()).filter(Boolean)}
function naturalLog(text){const meal=text.match(/breakfast|morning/i)?'Breakfast':text.match(/afternoon|lunch/i)?'Afternoon':text.match(/dinner|night|evening/i)?'Dinner':'Snacks';const found=[];for(const token of tokenizeNatural(text)){let best=null;for(const f of allFoods()){const names=[f.name,...(f.aliases||[]),...Object.keys(aliases).filter(a=>aliases[a]===f.id)];const name=names.sort((a,b)=>b.length-a.length).find(n=>new RegExp('\\b'+n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i').test(token));if(name){best={f,name};break}}if(!best)continue;const before=token.slice(0,token.toLowerCase().indexOf(best.name.toLowerCase()));const qm=before.match(/(\d+(?:\.\d+)?)\s*(kg|g|ml|piece|pieces|pcs|egg|eggs|medium|large|small)?\s*$/i);found.push({f:best.f,qty:qm?`${qm[1]} ${qm[2]||'g'}`:best.f.serving})}return {meal,found:[...new Map(found.map(x=>[x.f.id,x])).values()]}}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active')});
document.getElementById('add').onclick=()=>{const food=document.getElementById('food').value.trim(),qty=document.getElementById('qty').value.trim(),meal=document.getElementById('meal').value,st=document.getElementById('addStatus');if(!food){st.textContent='Choose a food first.';return}const r=addFoodByName(food,qty,meal);if(!r.ok){st.textContent='⚠️ No match. Nothing was calculated. Add a verified custom food first.';return}save();document.getElementById('food').value='';document.getElementById('qty').value='';st.textContent=`✓ Added ${r.item.food} using ${r.item.dataType==='database'?'a verified database value':r.item.dataType==='estimate'?'a reference estimate':'your custom value'}.`;render()};
document.getElementById('exportData')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aniket-nutrition-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
function renderReminderBanner(){const b=document.getElementById('reminderBanner');if(!b)return;const names={omega3:'Omega-3',d3:'Vitamin D3',b12:'Vitamin B12'};const pending=Object.entries(state.reminders).filter(([,v])=>v).map(([k])=>names[k]);b.hidden=!pending.length;b.textContent=pending.length?`⏰ Reminder enabled: ${pending.join(' · ')}. This is an in-app reminder preference; it does not set a supplement dose.`:''}
document.getElementById('foodSearch')?.addEventListener('input',renderFoodSearch);
document.querySelectorAll('[data-supp]').forEach(x=>x.onchange=()=>{state.reminders[x.dataset.supp]=x.checked;save()});
document.getElementById('saveRecipe')?.addEventListener('click',saveRecipe);
document.getElementById('saveCustom')?.addEventListener('click',()=>{const name=document.getElementById('customName').value.trim(),st=document.getElementById('customStatus');const values={kcal:Number(document.getElementById('customKcal').value),protein:Number(document.getElementById('customProtein').value)||0,carbs:Number(document.getElementById('customCarbs').value)||0,fat:Number(document.getElementById('customFat').value)||0,fiber:Number(document.getElementById('customFiber').value)||0};if(!name||!Number.isFinite(values.kcal)){st.textContent='Enter a name and verified calories.';return}const micronutrients={};for(const k of Object.keys(MICRO)){const el=document.getElementById('custom_'+k);if(el&&el.value!=='')micronutrients[k]=Number(el.value)||0}state.customFoods.push({id:'custom_'+crypto.randomUUID(),name,nutrients:{...values,...micronutrients},source:'User-entered verified label/value',sourceType:'user_entered',sourceId:null,foodState:'as-labelled',basis:'per 100 g as entered',ediblePortionPct:100,servingGrams:100});save();st.textContent='✓ Saved. This food is labelled user-entered, not database data.';['customName','customKcal','customProtein','customCarbs','customFat','customFiber',...Object.keys(MICRO).map(k=>'custom_'+k)].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});render()});
document.getElementById('aiAdd').onclick=()=>{const text=document.getElementById('aiText').value.trim(),st=document.getElementById('aiStatus');if(!text)return;const r=naturalLog(text);if(!r.found.length){st.textContent='⚠️ No known food found. Nothing was logged.';return}r.found.forEach(x=>dayItems().push(makeItem(x.f,x.qty,r.meal)));save();render();document.getElementById('aiText').value='';st.innerHTML=`✓ Interpreted ${r.found.length} known food(s) for <b>${r.meal}</b>. The nutrition engine performed the calculation.`};
document.getElementById('syncIfct')?.addEventListener('click',syncIFCT);
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('install').hidden=false});document.getElementById('install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('install').hidden=true}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
renderDataNotice();
render();
